### ISSUE TITLE
mod causing crash

### ISSUE THREAD

**Issue by TsplayerT** [TelepathicGrunt/WorldBlender#28]
I had several problems with the mod and all the errors were similar to these, in fact there are problems registered in different issues that occurred to me

[latest.log](https://github.com/TelepathicGrunt/WorldBlender/files/5742453/latest.log)
![Screenshot_3](https://user-images.githubusercontent.com/6465230/103142676-f19d3900-46e5-11eb-99d5-97f16b66ccd2.png)

**Comment by TelepathicGrunt** [comment]
I am not supporting my mods on Minecraft version older than latest (1.16.2+). Sorry. I just don't have to time to work on multiple mc versions of my mods. 

Although looking at the logs, it seems the issue is wildnature's features cannot be parsed into json for world blender's comparisons to work. Something in their feature is missing the element "shooter" which causes gson to crash here:
https://github.com/TelepathicGrunt/WorldBlender/blob/6e90650f0ade4270990abf3d38d8d9dbfa42c616/src/main/java/net/telepathicgrunt/worldblender/the_blender/FeatureGrouping.java#L368

I guess I should've used Throwable instead of Exception to make it skip entries that fail to be parsed to json back then.
