### ISSUE TITLE
Minecraft crashed when going into world blender dimension

### ISSUE THREAD

**Issue by DKLYNTLY** [TelepathicGrunt/WorldBlender#43]
debug.log: https://gist.github.com/Rubyz67/5b8c399c76e1cb8d8bf98899617a01e9
crash log: 
[crash-2021-08-22_19.05.45-server.txt](https://github.com/TelepathicGrunt/WorldBlender/files/7028305/crash-2021-08-22_19.05.45-server.txt)

**Comment by TelepathicGrunt** [comment]
The debug.log you gave got cut off before the actual crash. The latest.log file would be better to give as debug log files tends to be bloated much bigger and gist cut it off or copy/paste couldn't grab the whole thing.

But anyway, judging from the crashlog, this is being ran on a server with a massive amount of mods and the server is limited to 180 seconds for a tick before the watchdog will kill it. The watchdog is what keeps checking the server to see if it is stuck and if the server takes too long to do anything, the watchdog crashes the game to unstuck it.

So from this long, it seems like the server wasn't stuck but was running code at the time and crashes during Lycanite's WorldSpawnTrigger code that runs every tick. And since you mentioned you were entering world blender, it is possible that world blender, being bloated with so many mod's features and mobs and stuff, was making the server take so long. And then lycanite's WorldSpawnTrigger code was trying to load more chunks in world blender but ended up trying to load too many WB chunks which made the server take over 180 seconds in lycanite's code and then the watchdog came in and killed the server. It isn't really lycanite's fault but just how world blender chunks takes forever to load when there's too much worldgen stuff shoved into it.

If you feel like doing some testing, does removing lycanite let you into world blender? If not, try going into world blender's config and turn off the modded feature and structure import config entry so that the dimension is mainly vanilla and see if that makes the dimension fast enough to load into. If that config makes it work, then I'll try and give you a config file that blacklists some of the most intensive worldgen stuff from byg and better end as that might all that is needed to be blacklisted from world blender's world to keep it from making the server take to long to generate

**Comment by Rubyz67** [comment]
i will try to blacklist some mods and if that doesn't work then I will ask for a config file you made

**Comment by DKLYNTLY** [comment]
and here is the log: 
[latest.log](https://github.com/TelepathicGrunt/WorldBlender/files/7028511/latest.log)

**Comment by DKLYNTLY** [comment]
> The debug.log you gave got cut off before the actual crash. The latest.log file would be better to give as debug log files tends to be bloated much bigger and gist cut it off or copy/paste couldn't grab the whole thing.
> 
> But anyway, judging from the crashlog, this is being ran on a server with a massive amount of mods and the server is limited to 180 seconds for a tick before the watchdog will kill it. The watchdog is what keeps checking the server to see if it is stuck and if the server takes too long to do anything, the watchdog crashes the game to unstuck it.
> 
> So from this long, it seems like the server wasn't stuck but was running code at the time and crashes during Lycanite's WorldSpawnTrigger code that runs every tick. And since you mentioned you were entering world blender, it is possible that world blender, being bloated with so many mod's features and mobs and stuff, was making the server take so long. And then lycanite's WorldSpawnTrigger code was trying to load more chunks in world blender but ended up trying to load too many WB chunks which made the server take over 180 seconds in lycanite's code and then the watchdog came in and killed the server. It isn't really lycanite's fault but just how world blender chunks takes forever to load when there's too much worldgen stuff shoved into it.
> 
> If you feel like doing some testing, does removing lycanite let you into world blender? If not, try going into world blender's config and turn off the modded feature and structure import config entry so that the dimension is mainly vanilla and see if that makes the dimension fast enough to load into. If that config makes it work, then I'll try and give you a config file that blacklists some of the most intensive worldgen stuff from byg and better end as that might all that is needed to be blacklisted from world blender's world to keep it from making the server take to long to generate

[latest.log](https://github.com/TelepathicGrunt/WorldBlender/files/7034475/latest.log)
[debug.log](https://github.com/TelepathicGrunt/WorldBlender/files/7034476/debug.log)

**Comment by TelepathicGrunt** [comment]
Sorry i forgot about this for so long. But I went ahead and tried world blender with lycanite myself and no issue. If you are still using world blender, have you tried my suggestion of blacklisting a bunch of stuff from world blender's dimension? Or can you send me your modpack profile so I can see all your mod and configs and can try it myself to see what mod's stuff is taking up so much worldgen time in world blender's dimension.

**Comment by TelepathicGrunt** [comment]
Since there has been no response in a while and I cannot reproduce the issue, I'll close this issue report now
