### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by WenXin20** [TelepathicGrunt/WorldBlender#5]
`Minecraft v1.15.2`
`Forge v31.1.30`
`World Blender v1.3.2`

I got an error on load that says "World Blender encountered an error during the complete event phase: `null`"
[Log](https://gist.github.com/WenXin20/71f6d033a94ede25b28d8c8f3bad5201): Error starts at`[16:46:38]`

**Comment by TelepathicGrunt** [comment]
Bugs already?! AAAAAAAAAAAAAAAAA!!!

Now that I got that out of my system lol, I think I know what the problem is and how to fix it. Try this quick fix jar and see let me know if it fixes the issue for you. :)
[world_blender-1.15.2-1.3.2.zip](https://github.com/TelepathicGrunt/WorldBlender/files/4411797/world_blender-1.15.2-1.3.2.zip)

**Comment by WenXin20** [comment]
Yep, that fixed it, thanks!

**Comment by TelepathicGrunt** [comment]
Perfect! Thank you for reporting this issue!
